# Default
# -f "bv*+ba/b"

# Download and Merge Best Video and Best Audio
-f "bv+ba/b"
# --format "bv*[ext=webm]+ba[ext=webm][acodec=opus]"
# --format "bv*[ext=webm]+ba[ext=webm][acodec=opus]/b[ext=mp4]"
